[package]
name = "whurl"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
reqwest = { version = "0.10", features = ["json"] }
tokio = { version = "0.2", features = ["full"] }

[dependencies.clap]
version = "4.5.1"
features = ["cargo", "derive", "unicode", "wrap_help"]
